### ISSUE TITLE
Semicolon missing

### ISSUE THREAD

**Issue by jonnynux** [vicvega/chaltron#17]
Semicolon missing in the end of `&nbsp`:

https://github.com/vicvega/chaltron/blob/f712a0fb14b3a0254a03b4fb295a7200fb9cbe95/app/helpers/chaltron/ldap_helper.rb#L5

https://github.com/vicvega/chaltron/blob/f712a0fb14b3a0254a03b4fb295a7200fb9cbe95/app/helpers/chaltron/users_helper.rb#L4

**Comment by crondaemon** [comment]
Good catch. Can you send a pull request?
