### ISSUE TITLE
Multiple object in index

### ISSUE THREAD

**Issue by crondaemon** [vicvega/chaltron#2]
Scaffold indexes show multiple objects (show number of elements, pagination infos).

Reproducer: --> index --> show one element --> push back button in browser.

**Comment by vicvega** [comment]
It is a known issue in `datatables`

Here is a workaround
https://datatables.net/forums/discussion/36875/duplicate-wrapper-with-browser-forward-back-button

**Comment by vicvega** [comment]
Just released version `0.2.1`, including that workaround
