### ISSUE TITLE
Consider using data-order for sorting datatables

### ISSUE THREAD

**Issue by sektorcap** [vicvega/chaltron#8]
See https://www.datatables.net/examples/advanced_init/html5-data-attributes.html

**Comment by crondaemon** [comment]
Can you provide a use case?

**Comment by sektorcap** [comment]
No specific use case for the developer who uses chaltron.
Just a suggestion to use a different approach for sorting datatables in chaltron.
Using data-order you don't need to define the following line
https://github.com/vicvega/chaltron/blob/f39998eade4732004568602fbca3c2f48c7c5aaa/app/assets/javascripts/chaltron/datatables.js.coffee#L75

It should be useful if you need different date format in different tables.

**Comment by vicvega** [comment]
Good catch. I removed any dependency from `moment.js`. 

Each client side table (including datetime fields) can be easily ordered using `data-order` as you suggested
